export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  headline1: "우리 지구를 위한",
  headline2: "ECO 챌린지를 확인해보세요.",
  description2: "우리의 작은 실천이 지구를 살립니다.",
  buttonLabel: "챌린지로 Go!",
  imgStart: false,
  imgs: [
    "/img/challenge/001.png",
    "/img/challenge/002.png",
    "/img/challenge/003.png",
    "/img/challenge/004.png",
    "/img/challenge/005.png",
    "/img/challenge/006.png",
    "/img/challenge/007.png",
    "/img/challenge/008.png",
    "/img/challenge/009.png",
    "/img/challenge/010.png",
    "/img/challenge/011.png",
    "/img/challenge/012.png",
    "/img/challenge/013.png",
    "/img/challenge/014.png",
    "/img/challenge/015.png",
    "/img/challenge/016.png",
    "/img/challenge/017.png",
    "/img/challenge/018.png",
  ],
  alt: "eco",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "upload",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Mission Eco",
  headline: `머신러닝으로 학습 시킨
  이미지 인식을 경험해 보세요.`,
  description:
    "미션에 참여하기 위해 거쳐야 하는 관문이 있습니다! 해당 이미지가 미션에 적합한지 확인 후 에코로그를 남겨보세요.",
  buttonLabel: "미션참여하기",
  imgStart: true,
  img: "/gif/model.gif",
  alt: "eco",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "log",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Our Mission",
  headline: "환경을 위하는 우리, 우리의 이야기를 공유해요",
  description:
    "미션에 참여하기 위해 거쳐야 하는 관문이 있습니다! 해당 이미지가 미션에 적합한지 확인 후 에코로그를 남겨보세요.",
  buttonLabel: "Log 보러가기",
  imgStart: false,
  img: require("../../imges/svg-3.svg").default,
  alt: "eco",
  dark: true,
  primary: true,
  darkText: true,
};

export const homeObjFour = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Mission Eco",
  headline: "나만의 컬렉션이 완성됩니다.",
  description:
    "마이페이지에서는 챌린지를 통해 획득한 에코뱃지, 내가 좋아한 챌린지, 내가 작성한 게시물을 컬렉션으로 모아 볼 수 있어요.",
  buttonLabel: "나의 컬렉션 확인",
  imgStart: true,
  img: "/gif/mypage-test.gif",
  alt: "eco",
  dark: false,
  primary: false,
  darkText: true,
};
